\import Category
\import Paths
\import Unique
\import Universal.Terminal
\import Cartesian
\import Util

\func cartesianTerminal {C D : Precat} (tc : Terminal C) (td : Terminal D) : Terminal (C [x] D) \cowith
  | term => (tc.term, td.term)
  | terminal x =>
    \let | s1 : Singleton  => tc.terminal x.1
         | s2 : Singleton  => td.terminal x.2
    \in \new Singleton _ (s1.elem, s2.elem)
                       (\lam y z => pmap2 tuple (s1.singleton y.1 z.1) (s2.singleton y.2 z.2))